version: '2.4'
services:
  my-app:
    image: easy-walk:v2
    network_mode: host
    restart: always
    # Il documento raccomanda FORTEMENTE di mettere limiti di memoria
    mem_limit: 500m
    command: ["192.168.50.3", "--host-ip=192.168.50.5"]