version: '2.4'
services:
  easy-walk-app:
    image: easy-walk:v1
    container_name: easy-walk-container
    network_mode: host
    restart: always
    mem_limit: 500m
    logging:
      driver: journald